// ─── Assessment Step Definitions ───
// 31 questions exactly as specified

export const STEPS = [
  {
    id: 1,
    name: 'phone',
    type: 'phone',
    label: 'What is your phone number?',
    sublabel: 'We\'ll only use this to follow up on your Career GPS report.',
    prefix: '+1',
    placeholder: '(555) 000-0000',
    required: true,
  },
  {
    id: 2,
    name: 'visa',
    type: 'radio',
    label: 'What is your Visa Status?',
    sublabel: 'This helps us tailor job opportunities and sponsorship advice for you.',
    options: ['CPT', 'POST OPT (Initial OPT)', 'STEM OPT', 'H1', 'H4 EAD', 'L2 EAD', 'GC', 'USC', 'Other'],
    hasOther: true,
    required: true,
    autoAdvance: true,
  },
  {
    id: 3,
    name: 'relocate',
    type: 'radio',
    label: 'Are you open to relocate?',
    sublabel: 'Flexibility dramatically increases the number of opportunities available to you.',
    options: ['Yes', 'No'],
    required: true,
    autoAdvance: true,
  },
  {
    id: 4,
    name: 'location',
    type: 'input',
    label: 'What is your location preference?',
    sublabel: 'Enter cities, states, or "Remote" — separate multiple with commas.',
    placeholder: 'e.g., New York, TX, Remote',
    required: true,
  },
  {
    id: 5,
    name: 'resume',
    type: 'file',
    label: 'Upload your resume',
    sublabel: 'Our AI will analyze it for ATS compatibility and keyword gaps.',
    maxSizeMB: 5,
    required: true,
  },
  {
    id: 6,
    name: 'resumeVersions',
    type: 'input-na',
    label: 'How many resume versions do you have?',
    sublabel: 'Different versions tailored to different roles or industries.',
    placeholder: 'e.g., 3',
    inputType: 'number',
    naLabel: 'Not Applicable',
    required: true,
  },
  {
    id: 7,
    name: 'atsScore',
    type: 'input-na',
    label: 'What is your latest ATS score?',
    sublabel: 'From tools like Jobscan, Resume Worded, or similar.',
    placeholder: 'e.g., 85%',
    inputType: 'text',
    naLabel: "I Don't Know",
    required: true,
  },
  {
    id: 8,
    name: 'customizeResume',
    type: 'radio',
    label: 'Do you customize your resume for every Job Description?',
    sublabel: 'Tailored resumes get 2x more callbacks than generic ones.',
    options: ['Yes', 'No'],
    required: true,
    autoAdvance: true,
  },
  {
    id: 9,
    name: 'employmentGap',
    type: 'radio',
    label: 'Do you have any employment gap?',
    sublabel: 'Gaps are common — knowing about them helps us advise you on framing.',
    options: ['Yes', 'No'],
    required: true,
    autoAdvance: true,
  },
  {
    id: 10,
    name: 'metrics',
    type: 'radio',
    label: 'Does your resume include measurable impact metrics?',
    sublabel: 'e.g., "Increased revenue by 23%" or "Led a team of 8 engineers".',
    options: ['Yes', 'No'],
    required: true,
    autoAdvance: true,
  },
  {
    id: 11,
    name: 'linkedin',
    type: 'input',
    label: 'Share your LinkedIn Profile URL',
    sublabel: '85% of recruiters check LinkedIn before reaching out.',
    placeholder: 'https://linkedin.com/in/yourprofile',
    inputType: 'url',
    required: true,
  },
  {
    id: 12,
    name: 'linkedinOpt',
    type: 'radio',
    label: 'Is your LinkedIn profile fully optimized?',
    sublabel: 'All-Star status, keyword-rich headline, featured section, and 500+ connections.',
    options: ['Yes', 'No', 'Not Sure'],
    required: true,
    autoAdvance: true,
  },
  {
    id: 13,
    name: 'linkedinCon',
    type: 'input-na',
    label: 'How many new LinkedIn connections do you add per week?',
    sublabel: 'Consistent networking compounds over time.',
    placeholder: 'e.g., 20',
    inputType: 'number',
    naLabel: 'Not Applicable / Don\'t Track',
    required: true,
  },
  {
    id: 14,
    name: 'coldEmails',
    type: 'input-na',
    label: 'How many cold emails or LinkedIn messages do you send per week?',
    sublabel: 'Direct outreach bypasses the ATS and gets eyes on your profile.',
    placeholder: 'e.g., 15',
    inputType: 'number',
    naLabel: 'Not Applicable / Don\'t Track',
    required: true,
  },
  {
    id: 15,
    name: 'consultancy',
    type: 'radio',
    label: 'Are you currently working with any consultancy?',
    sublabel: 'Understanding your current support structure helps us identify gaps.',
    options: [
      'No',
      'Working with Freelancer',
      'C2C Consultancy (Free)',
      'W2 Fulltime (Paid Consultancy)',
    ],
    required: true,
    autoAdvance: true,
  },
  {
    id: 16,
    name: 'appsDay',
    type: 'input',
    label: 'How many applications do you send per day?',
    sublabel: 'Quality over quantity matters — but we need the baseline.',
    placeholder: 'e.g., 10',
    inputType: 'number',
    required: true,
  },
  {
    id: 17,
    name: 'easyApply',
    type: 'input',
    label: 'How many Easy (Quick) Apply applications per day?',
    sublabel: 'One-click apply tends to have lower response rates than tailored applications.',
    placeholder: 'e.g., 5',
    inputType: 'number',
    required: true,
  },
  {
    id: 18,
    name: 'aiScreen',
    type: 'input-na',
    label: 'How many AI screening calls have you received?',
    sublabel: 'Automated first-round calls from tools like HireVue or Paradox.',
    placeholder: 'e.g., 2',
    inputType: 'number',
    naLabel: 'None / N/A',
    required: true,
  },
  {
    id: 19,
    name: 'humanScreen',
    type: 'input-na',
    label: 'How many human screening calls have you received?',
    sublabel: 'Phone or video calls from a recruiter or HR.',
    placeholder: 'e.g., 1',
    inputType: 'number',
    naLabel: 'None / N/A',
    required: true,
  },
  {
    id: 20,
    name: 'assessments',
    type: 'input-na',
    label: 'How many assessments have you received?',
    sublabel: 'Technical tests, take-home assignments, or aptitude tests.',
    placeholder: 'e.g., 3',
    inputType: 'number',
    naLabel: 'None / N/A',
    required: true,
  },
  {
    id: 21,
    name: 'assessScore',
    type: 'input-na',
    label: 'What is your average assessment score?',
    sublabel: 'If you received score feedback from any test.',
    placeholder: 'e.g., 80%',
    inputType: 'text',
    naLabel: 'N/A / Don\'t Know',
    required: true,
  },
  {
    id: 22,
    name: 'assessType',
    type: 'checkbox',
    label: 'What types of assessments have you received?',
    sublabel: 'Select all that apply.',
    options: [
      'Technical Assessment (Coding, SQL, System Design, Cloud, Cybersecurity)',
      'Aptitude / Logical Reasoning Assessment',
      'Behavioral / Personality Assessment',
      'AI / Video Assessment (HireVue, SparkHire, AI Screening, etc.)',
      'Take-Home Assignment / Case Study / Project',
      'None Received',
    ],
    required: true,
    autoAdvance: false,
  },
  {
    id: 23,
    name: 'mockInterviews',
    type: 'radio',
    label: 'Do you practice mock interviews?',
    sublabel: 'Regular practice can increase your offer rate by up to 40%.',
    options: ['Yes', 'No'],
    required: true,
    autoAdvance: true,
  },
  {
    id: 24,
    name: 'codeInterviews',
    type: 'radio',
    label: 'Do you struggle with coding interviews?',
    sublabel: 'Be honest — this helps us recommend the right prep resources.',
    options: ['Yes', 'No', 'Not Applicable (Not a Developer)'],
    required: true,
    autoAdvance: true,
  },
  {
    id: 25,
    name: 'feedback',
    type: 'checkbox',
    label: 'What is the typical interview feedback you receive?',
    sublabel: 'Select all patterns you\'ve experienced.',
    options: [
      'Your profile does not match our requirements',
      'We found a candidate who is a better fit (Hire Someone Internally)',
      'Overqualified or Underqualified for the position',
      'Looking for local candidates only',
      'Rejected after assessment or interview (No Response After this)',
      'Looking for GC / USC only (Sponsorship not available)',
      'Position put on hold / Budget constraints',
      'Rarely receive rejection emails or feedback',
      'Hiring Manager / Decision Maker Unavailable (Leave, Vacation, Internal Delays)',
      'Company is interviewing other candidates',
      'No response / Ghosted',
      'Other',
    ],
    hasOther: true,
    required: true,
    autoAdvance: false,
  },
  {
    id: 26,
    name: 'hoursDay',
    type: 'input',
    label: 'How many hours per day do you invest in your job search?',
    sublabel: 'This helps us understand how much you can realistically implement.',
    placeholder: 'e.g., 4',
    inputType: 'number',
    required: true,
  },
  {
    id: 27,
    name: 'biggestChallenge',
    type: 'textarea',
    label: 'What is your biggest challenge in your job search?',
    sublabel: 'Be as specific as possible — this directly shapes your Career GPS report.',
    placeholder: 'Describe your main obstacle...',
    required: true,
  },
  {
    id: 28,
    name: 'triedImprove',
    type: 'textarea',
    label: 'What have you already tried to improve your job search?',
    sublabel: 'List any services, tools, courses, or strategies you\'ve attempted.',
    placeholder: 'List services, tools, or strategies...',
    required: true,
  },
  {
    id: 29,
    name: 'aiTools',
    type: 'checkbox',
    label: 'Which AI or automation tools have you used in your job search?',
    sublabel: 'Select all that apply.',
    options: [
      'ATS Resume Keyword Matching Tool',
      'AI Resume Optimization Tool',
      'AI Mock Interview Platform',
      'AI Coding Interview Preparation Tool',
      'Job Application Automation Tool (Auto Apply)',
      'One-Click Job Application Autofill Tool',
      'AI Email & Recruiter Follow-up Automation',
      'LinkedIn Networking Automation Tool',
      'LinkedIn Post & Comment Automation Tool',
      'Job Aggregator Tool',
      'Layoff & Hiring Tracker Tool',
      'None of the Above',
    ],
    required: true,
    autoAdvance: false,
  },
  {
    id: 30,
    name: 'strategies',
    type: 'checkbox',
    label: 'Which job search strategies are you currently using?',
    sublabel: 'Select all that apply.',
    options: [
      'Resume customized for every Job Description',
      'LinkedIn Profile Optimization',
      'LinkedIn Recruiter Visibility Optimization (Open-to-Work & Hidden Settings)',
      'Active networking with recruiters, hiring managers, and alumni networks',
      'Undo Hidden iPhone Settings That May Block Recruiter Calls',
      'Cold (Mass) emailing recruiters & hiring managers',
      'Employee Referral Strategy',
      'Active member of Job Search Communities (Slack, Discord, WhatsApp, Telegram, LinkedIn Groups)',
      'None of the Above',
    ],
    required: true,
    autoAdvance: false,
  },
  {
    id: 31,
    name: 'investGuidance',
    type: 'radio',
    label: 'Are you willing to invest in structured career guidance if it helps you get results faster?',
    sublabel: 'Candidates with professional career coaching land roles 3x faster on average.',
    options: ['Yes', 'No'],
    required: true,
    autoAdvance: true,
    isSubmitStep: true,
  },
]
